# Generated by Django 4.2.5 on 2023-09-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости"},
        ),
        migrations.AlterField(
            model_name="articles",
            name="date",
            field=models.DateTimeField(verbose_name="Дата публикации"),
        ),
    ]
