# Generated by Django 4.2.5 on 2023-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_articles_options_alter_articles_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.IntegerField(
                        choices=[
                            (1, "Недвижимость"),
                            (2, "Авто"),
                            (3, "Инструмент"),
                            (4, "Разное"),
                        ],
                        verbose_name="topic",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="articles",
            name="anons",
            field=models.CharField(max_length=250, verbose_name="Анонс"),
        ),
        migrations.AlterField(
            model_name="articles",
            name="full_text",
            field=models.TextField(verbose_name="Статья"),
        ),
        migrations.AlterField(
            model_name="articles",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
    ]
