# Generated by Django 4.2.5 on 2023-09-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_articles_options_alter_articles_anons_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ChoiceTopic",),
        migrations.AlterField(
            model_name="articles",
            name="title",
            field=models.ImageField(
                choices=[(1, "Продам"), (1, "Куплю")],
                upload_to="",
                verbose_name="Категория",
            ),
        ),
    ]
