# Generated by Django 4.2.5 on 2023-09-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_delete_choicetopic_alter_articles_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="anons",
            field=models.IntegerField(
                choices=[
                    (1, "Недвижимость"),
                    (2, "Авто"),
                    (3, "Инструмент"),
                    (4, "Разное"),
                ],
                verbose_name="Тема",
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="title",
            field=models.ImageField(
                choices=[(1, "Продам"), (2, "Куплю"), (3, "Меняю"), (4, "Разное")],
                upload_to="",
                verbose_name="Категория",
            ),
        ),
    ]
