# Generated by Django 4.2.5 on 2023-09-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_articles_anons_alter_articles_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="title",
            field=models.IntegerField(
                choices=[(1, "Продам"), (2, "Куплю"), (3, "Меняю"), (4, "Разное")],
                verbose_name="Категория",
            ),
        ),
    ]
