# Generated by Django 4.2.5 on 2023-09-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_articles_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="title",
            field=models.TextField(verbose_name="Тема объявления, например, ПРОДАМ"),
        ),
    ]
